const SUPABASE_URL = 'https://oplujvnyutmxfpdewezb.supabase.co';
const SUPABASE_KEY = 'sb_publishable_dd1dOvBAwPgA1AeqNOQHDg_Wdjvf-ze';
let sb, query = '', vastgoedData = [], rawProperties = [], rawContracts = [], rawTenants = [], rawMaintenance = [];
const euro = n => new Intl.NumberFormat('nl-NL', {style:'currency', currency:'EUR', maximumFractionDigits:0}).format(Number(n || 0));
const dateFmt = s => s ? new Date(s).toLocaleDateString('nl-NL') : '-';
const statusBadge = st => `<span class="badge ${st[1]}">${st[0]}</span>`;
const el = id => document.getElementById(id);
const numOrNull = v => v === '' || v === null ? null : Number(v);
const emptyToNull = v => v === '' ? null : v;

function daysUntil(dateString){ if(!dateString) return null; const d=new Date(dateString); if(Number.isNaN(d.getTime())) return null; const t=new Date(); t.setHours(0,0,0,0); d.setHours(0,0,0,0); return Math.ceil((d-t)/(1000*60*60*24)); }
function getDateStatus(dateString, warningDays=365, dangerDays=90){ const days=daysUntil(dateString); if(days===null) return ['Controle nodig','warning']; if(days<0) return ['Verlopen','danger']; if(days<=dangerDays) return [`Binnen ${dangerDays} dagen`,'danger']; if(days<=warningDays) return [`Binnen ${warningDays} dagen`,'warning']; return ['Op orde','ok']; }
function propName(p){ return p?.name || [p?.address,p?.house_number].filter(Boolean).join(' ') || 'Onbekend object'; }
function propertyOptions(selected=''){ return rawProperties.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${propName(p)}</option>`).join(''); }
function tenantOptions(selected=''){ return rawTenants.map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${t.name}</option>`).join(''); }

function normalize(properties, contracts, tenants, maintenance){
  const tenantById=Object.fromEntries(tenants.map(t=>[t.id,t]));
  const contractsByProperty={}; contracts.forEach(c=>{(contractsByProperty[c.property_id] ||= []).push(c)});
  const maintenanceByProperty={}; maintenance.forEach(m=>{(maintenanceByProperty[m.property_id] ||= []).push(m)});
  return properties.map(p=>{
    const contract=(contractsByProperty[p.id]||[])[0]||{};
    const tenant=tenantById[contract.tenant_id]||{};
    const plannedMaintenance=(maintenanceByProperty[p.id]||[])[0]||{};
    const rentPm=p.monthly_rent ?? contract.monthly_rent ?? 0;
    const rentPj=p.yearly_rent ?? (Number(rentPm||0)*12);
    const contractEnd=contract.end_date || p.end_date;
    const noticeDate=contract.notice_date || p.notice_date;
    const scopeDate=p.scope_valid_until || plannedMaintenance.planned_date;
    return {id:p.id, object:propName(p), straatnaam:p.address||'', huisnummer:p.house_number||'', stad:p.city||'', huurder:tenant.name||p.tenant_name||'-', email:tenant.email||p.email||'', telefoon:tenant.phone||p.phone||'', huur_pm:rentPm, huur_pj:rentPj, servicekosten:p.service_costs||0, waarborgsom:p.deposit||0, energielabel:p.energy_label||'-', energielabel_geldig_tot:p.energy_label_valid_until||'', maand_huurverhoging:p.rent_increase_month||'', einddatum_contract:contractEnd, opzegdatum:noticeDate, scope_inspectie_geldig_tot:scopeDate, onderhoud_titel:plannedMaintenance.title||'Scope-inspectie', status_contract:getDateStatus(contractEnd,365,90), status_opzeg:getDateStatus(noticeDate,365,90), status_scope:getDateStatus(scopeDate,365,90)};
  });
}
function showLogin(){ el('loginView').classList.remove('hidden'); el('appView').classList.add('hidden'); }
function showApp(){ el('loginView').classList.add('hidden'); el('appView').classList.remove('hidden'); }
async function checkSession(){ const {data}=await sb.auth.getSession(); if(data.session){showApp(); await loadData();} else showLogin(); }
async function loadData(){
  try{
    const [pr,cr,tr,mr]=await Promise.all([sb.from('properties').select('*').order('created_at',{ascending:false}), sb.from('contracts').select('*'), sb.from('tenants').select('*'), sb.from('maintenance').select('*')]);
    [pr,cr,tr,mr].forEach(r=>{if(r.error) throw r.error});
    rawProperties=pr.data||[]; rawContracts=cr.data||[]; rawTenants=tr.data||[]; rawMaintenance=mr.data||[];
    vastgoedData=normalize(rawProperties, rawContracts, rawTenants, rawMaintenance);
    el('statusText').textContent=`Live data uit Supabase. Laatst geladen: ${new Date().toLocaleTimeString('nl-NL')}`;
    render();
  }catch(error){ console.error(error); el('statusText').textContent='Kan data niet laden.'; el('attentionList').innerHTML=`<div class="alert danger"><strong>Fout bij laden</strong>${error.message}</div>`; }
}
function filtered(){ return vastgoedData.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())); }
function notificationItems(data){ const items=[]; data.forEach(r=>{ if(r.status_opzeg[1]!=='ok') items.push({sev:r.status_opzeg[1],title:`Opzegdatum: ${r.object}`,text:`Opzegdatum ${dateFmt(r.opzegdatum)}. Contract eindigt op ${dateFmt(r.einddatum_contract)}.`}); if(r.status_contract[1]!=='ok') items.push({sev:r.status_contract[1],title:`Contract: ${r.object}`,text:`Contractstatus: ${r.status_contract[0]}. Einddatum ${dateFmt(r.einddatum_contract)}.`}); if(r.status_scope[1]!=='ok') items.push({sev:r.status_scope[1],title:`Onderhoud/inspectie: ${r.object}`,text:`Datum: ${dateFmt(r.scope_inspectie_geldig_tot)}.`}); }); return items; }
function render(){
  const data=filtered(), notes=notificationItems(data);
  el('totalObjects').textContent=data.length; el('totalRent').textContent=euro(data.reduce((a,b)=>a+Number(b.huur_pj||0),0)); el('urgentCount').textContent=notes.filter(n=>n.sev==='danger').length; el('contractSoon').textContent=data.filter(r=>r.status_contract[1]!=='ok').length;
  el('attentionList').innerHTML=notes.slice(0,5).map(n=>`<div class="alert ${n.sev}"><strong>${n.title}</strong>${n.text}</div>`).join('') || '<p>Geen aandachtspunten gevonden.</p>';
  el('notificationList').innerHTML=notes.map(n=>`<div class="alert ${n.sev}"><strong>${n.title}</strong>${n.text}</div>`).join('') || '<p>Geen meldingen gevonden.</p>';
  el('objectGrid').innerHTML=data.map(r=>`<article class="objectCard"><h3>${r.object}</h3><div class="meta">Huurder: ${r.huurder}</div><div class="row"><span>Huur p/m</span><strong>${euro(r.huur_pm)}</strong></div><div class="row"><span>Jaarhuur</span><strong>${euro(r.huur_pj)}</strong></div><div class="row"><span>Energielabel</span><strong>${r.energielabel}</strong></div><div class="row"><span>Contract</span>${statusBadge(r.status_contract)}</div><div class="row"><span>Opzegdatum</span>${statusBadge(r.status_opzeg)}</div><div class="row"><span>Onderhoud/inspectie</span>${statusBadge(r.status_scope)}</div><button class="smallBtn" onclick="openEditProperty('${r.id}')">Bewerken</button></article>`).join('') || '<p>Geen objecten gevonden.</p>';
  el('tenantTable').innerHTML=`<tr><th>Naam</th><th>E-mail</th><th>Telefoon</th><th>Actie</th></tr>`+rawTenants.map(t=>`<tr><td>${t.name||''}</td><td>${t.email||''}</td><td>${t.phone||''}</td><td><button class="smallBtn" onclick="openEditTenant('${t.id}')">Bewerken</button></td></tr>`).join('');
  el('contractTable').innerHTML=`<tr><th>Object</th><th>Huurder</th><th>Huur p/m</th><th>Einddatum</th><th>Opzegdatum</th><th>Status</th><th>Actie</th></tr>`+rawContracts.map(c=>{ const p=rawProperties.find(x=>x.id===c.property_id); const t=rawTenants.find(x=>x.id===c.tenant_id); const st=getDateStatus(c.end_date,365,90); return `<tr><td>${propName(p)}</td><td>${t?.name||'-'}</td><td>${euro(c.monthly_rent)}</td><td>${dateFmt(c.end_date)}</td><td>${dateFmt(c.notice_date)}</td><td>${statusBadge(st)}</td><td><button class="smallBtn" onclick="openEditContract('${c.id}')">Bewerken</button></td></tr>` }).join('');
  el('maintenanceTable').innerHTML=`<tr><th>Object</th><th>Type</th><th>Datum</th><th>Status</th><th>Prioriteit</th><th>Actie</th></tr>`+rawMaintenance.map(m=>{ const p=rawProperties.find(x=>x.id===m.property_id); const st=getDateStatus(m.planned_date,365,90); return `<tr><td>${propName(p)}</td><td>${m.title||''}</td><td>${dateFmt(m.planned_date)}</td><td>${statusBadge(st)}</td><td>${m.priority||''}</td><td><button class="smallBtn" onclick="openEditMaintenance('${m.id}')">Bewerken</button></td></tr>` }).join('');
}
function fillSelects(){ el('contractProperty').innerHTML=propertyOptions(); el('contractTenant').innerHTML=tenantOptions(); el('maintenanceProperty').innerHTML=propertyOptions(); }
function closeModal(id){ el(id).classList.add('hidden'); }

function openNewProperty(){ el('modalTitle').textContent='Nieuw object'; el('propertyForm').reset(); el('propertyId').value=''; el('propertyStatus').value='Actief'; el('deletePropertyBtn').classList.add('hidden'); el('propertyMessage').textContent=''; el('propertyModal').classList.remove('hidden'); }
window.openEditProperty=function(id){ const p=rawProperties.find(x=>x.id===id); if(!p)return; el('modalTitle').textContent='Object bewerken'; el('propertyId').value=p.id; el('propertyName').value=p.name||''; el('propertyAddress').value=p.address||''; el('propertyHouseNumber').value=p.house_number||''; el('propertyCity').value=p.city||''; el('propertyType').value=p.property_type||''; el('propertyStatus').value=p.status||'Actief'; el('propertyMonthlyRent').value=p.monthly_rent||''; el('propertyYearlyRent').value=p.yearly_rent||''; el('propertyServiceCosts').value=p.service_costs||''; el('propertyDeposit').value=p.deposit||''; el('propertyEnergyLabel').value=p.energy_label||''; el('propertyEnergyValidUntil').value=p.energy_label_valid_until||''; el('propertyRentIncreaseMonth').value=p.rent_increase_month||''; el('propertyScopeValidUntil').value=p.scope_valid_until||''; el('deletePropertyBtn').classList.remove('hidden'); el('propertyMessage').textContent=''; el('propertyModal').classList.remove('hidden'); }
async function saveProperty(e){ e.preventDefault(); const id=el('propertyId').value; const payload={name:el('propertyName').value,address:emptyToNull(el('propertyAddress').value),house_number:emptyToNull(el('propertyHouseNumber').value),city:emptyToNull(el('propertyCity').value),property_type:emptyToNull(el('propertyType').value),status:el('propertyStatus').value||'Actief',monthly_rent:numOrNull(el('propertyMonthlyRent').value),yearly_rent:numOrNull(el('propertyYearlyRent').value),service_costs:numOrNull(el('propertyServiceCosts').value),deposit:numOrNull(el('propertyDeposit').value),energy_label:emptyToNull(el('propertyEnergyLabel').value),energy_label_valid_until:emptyToNull(el('propertyEnergyValidUntil').value),rent_increase_month:emptyToNull(el('propertyRentIncreaseMonth').value),scope_valid_until:emptyToNull(el('propertyScopeValidUntil').value)}; const result=id?await sb.from('properties').update(payload).eq('id',id):await sb.from('properties').insert(payload); if(result.error){el('propertyMessage').textContent=result.error.message;return;} closeModal('propertyModal'); await loadData(); }
async function deleteProperty(){ const id=el('propertyId').value; if(!id || !confirm('Object verwijderen?')) return; const {error}=await sb.from('properties').delete().eq('id',id); if(error){el('propertyMessage').textContent=error.message;return;} closeModal('propertyModal'); await loadData(); }

function openNewTenant(){ el('tenantModalTitle').textContent='Nieuwe huurder'; el('tenantForm').reset(); el('tenantId').value=''; el('deleteTenantBtn').classList.add('hidden'); el('tenantMessage').textContent=''; el('tenantModal').classList.remove('hidden'); }
window.openEditTenant=function(id){ const t=rawTenants.find(x=>x.id===id); if(!t)return; el('tenantModalTitle').textContent='Huurder bewerken'; el('tenantId').value=t.id; el('tenantName').value=t.name||''; el('tenantEmail').value=t.email||''; el('tenantPhone').value=t.phone||''; el('deleteTenantBtn').classList.remove('hidden'); el('tenantMessage').textContent=''; el('tenantModal').classList.remove('hidden'); }
async function saveTenant(e){ e.preventDefault(); const id=el('tenantId').value; const payload={name:el('tenantName').value,email:emptyToNull(el('tenantEmail').value),phone:emptyToNull(el('tenantPhone').value)}; const result=id?await sb.from('tenants').update(payload).eq('id',id):await sb.from('tenants').insert(payload); if(result.error){el('tenantMessage').textContent=result.error.message;return;} closeModal('tenantModal'); await loadData(); }
async function deleteTenant(){ const id=el('tenantId').value; if(!id || !confirm('Huurder verwijderen?')) return; const {error}=await sb.from('tenants').delete().eq('id',id); if(error){el('tenantMessage').textContent=error.message;return;} closeModal('tenantModal'); await loadData(); }

function openNewContract(){ fillSelects(); el('contractModalTitle').textContent='Nieuw contract'; el('contractForm').reset(); el('contractId').value=''; el('contractStatus').value='Actief'; el('deleteContractBtn').classList.add('hidden'); el('contractMessage').textContent=''; el('contractModal').classList.remove('hidden'); }
window.openEditContract=function(id){ const c=rawContracts.find(x=>x.id===id); if(!c)return; fillSelects(); el('contractModalTitle').textContent='Contract bewerken'; el('contractId').value=c.id; el('contractProperty').value=c.property_id||''; el('contractTenant').value=c.tenant_id||''; el('contractStart').value=c.start_date||''; el('contractEnd').value=c.end_date||''; el('contractNotice').value=c.notice_date||''; el('contractRent').value=c.monthly_rent||''; el('contractStatus').value=c.status||'Actief'; el('deleteContractBtn').classList.remove('hidden'); el('contractMessage').textContent=''; el('contractModal').classList.remove('hidden'); }
async function saveContract(e){ e.preventDefault(); const id=el('contractId').value; const payload={property_id:el('contractProperty').value,tenant_id:el('contractTenant').value,start_date:emptyToNull(el('contractStart').value),end_date:emptyToNull(el('contractEnd').value),notice_date:emptyToNull(el('contractNotice').value),monthly_rent:numOrNull(el('contractRent').value),status:el('contractStatus').value||'Actief'}; const result=id?await sb.from('contracts').update(payload).eq('id',id):await sb.from('contracts').insert(payload); if(result.error){el('contractMessage').textContent=result.error.message;return;} closeModal('contractModal'); await loadData(); }
async function deleteContract(){ const id=el('contractId').value; if(!id || !confirm('Contract verwijderen?')) return; const {error}=await sb.from('contracts').delete().eq('id',id); if(error){el('contractMessage').textContent=error.message;return;} closeModal('contractModal'); await loadData(); }

function openNewMaintenance(){ fillSelects(); el('maintenanceModalTitle').textContent='Nieuwe onderhoudstaak'; el('maintenanceForm').reset(); el('maintenanceId').value=''; el('maintenanceStatus').value='Open'; el('maintenancePriority').value='Normaal'; el('deleteMaintenanceBtn').classList.add('hidden'); el('maintenanceMessage').textContent=''; el('maintenanceModal').classList.remove('hidden'); }
window.openEditMaintenance=function(id){ const m=rawMaintenance.find(x=>x.id===id); if(!m)return; fillSelects(); el('maintenanceModalTitle').textContent='Onderhoud bewerken'; el('maintenanceId').value=m.id; el('maintenanceProperty').value=m.property_id||''; el('maintenanceTitle').value=m.title||''; el('maintenanceDescription').value=m.description||''; el('maintenanceDate').value=m.planned_date||''; el('maintenanceCost').value=m.cost||''; el('maintenanceStatus').value=m.status||'Open'; el('maintenancePriority').value=m.priority||'Normaal'; el('deleteMaintenanceBtn').classList.remove('hidden'); el('maintenanceMessage').textContent=''; el('maintenanceModal').classList.remove('hidden'); }
async function saveMaintenance(e){ e.preventDefault(); const id=el('maintenanceId').value; const payload={property_id:el('maintenanceProperty').value,title:el('maintenanceTitle').value,description:emptyToNull(el('maintenanceDescription').value),planned_date:emptyToNull(el('maintenanceDate').value),cost:numOrNull(el('maintenanceCost').value),status:el('maintenanceStatus').value||'Open',priority:el('maintenancePriority').value||'Normaal'}; const result=id?await sb.from('maintenance').update(payload).eq('id',id):await sb.from('maintenance').insert(payload); if(result.error){el('maintenanceMessage').textContent=result.error.message;return;} closeModal('maintenanceModal'); await loadData(); }
async function deleteMaintenance(){ const id=el('maintenanceId').value; if(!id || !confirm('Onderhoudstaak verwijderen?')) return; const {error}=await sb.from('maintenance').delete().eq('id',id); if(error){el('maintenanceMessage').textContent=error.message;return;} closeModal('maintenanceModal'); await loadData(); }

function init(){
  if(!window.supabase){ el('loginError').textContent='Supabase library niet geladen. Ververs de pagina.'; return; }
  sb=window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
  document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active')); btn.classList.add('active'); document.querySelectorAll('.page').forEach(p=>p.classList.remove('active')); el(btn.dataset.page).classList.add('active'); el('pageTitle').textContent=btn.textContent; }));
  el('loginBtn').addEventListener('click', async()=>{ el('loginError').textContent='Bezig met inloggen...'; const email=el('email').value.trim(); const password=el('password').value; const {error}=await sb.auth.signInWithPassword({email,password}); if(error){ el('loginError').textContent='Inloggen mislukt: '+error.message; return;} el('loginError').textContent=''; showApp(); await loadData(); });
  el('password').addEventListener('keydown', e=>{ if(e.key==='Enter') el('loginBtn').click(); });
  el('logoutBtn').addEventListener('click', async()=>{ await sb.auth.signOut(); vastgoedData=[]; showLogin(); });
  el('search').addEventListener('input', e=>{ query=e.target.value; render(); });
  el('newPropertyBtn').addEventListener('click', openNewProperty); el('closePropertyModalBtn').addEventListener('click', ()=>closeModal('propertyModal')); el('propertyForm').addEventListener('submit', saveProperty); el('deletePropertyBtn').addEventListener('click', deleteProperty);
  el('newTenantBtn').addEventListener('click', openNewTenant); el('closeTenantModalBtn').addEventListener('click', ()=>closeModal('tenantModal')); el('tenantForm').addEventListener('submit', saveTenant); el('deleteTenantBtn').addEventListener('click', deleteTenant);
  el('newContractBtn').addEventListener('click', openNewContract); el('closeContractModalBtn').addEventListener('click', ()=>closeModal('contractModal')); el('contractForm').addEventListener('submit', saveContract); el('deleteContractBtn').addEventListener('click', deleteContract);
  el('newMaintenanceBtn').addEventListener('click', openNewMaintenance); el('closeMaintenanceModalBtn').addEventListener('click', ()=>closeModal('maintenanceModal')); el('maintenanceForm').addEventListener('submit', saveMaintenance); el('deleteMaintenanceBtn').addEventListener('click', deleteMaintenance);
  checkSession();
}
document.addEventListener('DOMContentLoaded', init);
